repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-case-conflict

- repo: https://github.com/Azure4DevOps/check-azure-bicep
  rev: v0.4.1
  hooks:
    - id: check-azure-bicep
