name: CoreInfra CICD

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '/CoreInfra/*'
    exclude:
      - '/**/*.md'


variables:
  SolutionPath: '/CoreInfra/'
  Location: 'eastus2'
  # vmImageName: 'ubuntu-latest'

  # azureServiceConnection: '<your-connection-name>'
  # resourceGroupName: 'exampleRG'
  # location: '<your-resource-group-location>'
  # templateFile: 'main.bicep'
pool:
  vmImage: 'Default'

stages:
- stage: Build
  displayName: 'Build (CI)'
  jobs:
  - job: Build
    steps:
    - script: |
        ls -al

      displayName: "Run Build Steps"
      workingDirectory: ${{ variables.SolutionPath }}
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'ES-CE-LR-INT JINLE(7386cd39-b109-4cc6-bb80-bf12413d0a99)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub validate \
            --name "CoreInfra-$(Build.BuildNumber)" \
            --location ${{ variables.Location }} \
            --template-file main.bicep \
            --parameters ./parameters/dev.json \
            --parameters ./parameters/shared.json
    

#   - job: Validate

# - stage: Deploy
#   displayName: 'Deploy (CD)'
#   jobs:
#   - job: Deploy
#     steps:
    