name: Publish CoreInfra docs
on:
  workflow_dispatch:
  push:
    branches: [ main, feature/auto-docs ]
    paths:
      - 'CoreInfra/*.bicep'
      - '.github/workflows/.coreinfra.generate_docs.yml'
env:
  inputPath: CoreInfra/coreinfra.bicep
  outputPath: CoreInfra/CoreInfra.md
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        pwd
        echo "Input path: ${{ env.inputPath }}"
        ls -al CoreInfra

        echo "Working Dir"
        ls -al ./


        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash


    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       az bicep build \
    #         --file ${{ env.inputPath }} \
    #         --outfile ${{ env.inputPath }}.json

    - name: Bicep Build
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: '${{github.workspace}}/${{ env.inputPath }}'
        outputFilePath: ${{ env.inputPath }}.json

    # Generate markdown files using PSDocs
    # Scan for Azure template file recursively in sub-directories
    # Then generate a docs using a standard naming convention. i.e. <name>_<version>.md
    - name: Generate docs
      uses: microsoft/ps-docs@v0.1.0
      with:
        conventions: Azure.NameByParentPath
        modules: PSDocs.Azure
        inputPath: ${{ env.inputPath }}.json
        # outputPath: '${{ env.GITHUB_WORKSPACE }}/${{ env.outputPath }}'
        prerelease: true
