name: 'CloudOps Team - CoreInfra Deploy'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: 'Remove the deployment instead of deploying it'
        required: false
        default: false
  push:
    branches:
      - main
    paths:
      - '.github/workflows/clopsteam.coreinfra.deploy.yml'
      - 'CoreInfra/main.bicep'
      - 'CoreInfra/parameters/clopsTeam.json'

env:
  scope: 'subscription'
  region: 'eastus2'
  resourceGroupName: 'CoreInfraBicepLive'
  solutionPath: 'CoreInfra'
  solutionDeploymentParamsPath: 'CoreInfra/parameters/clopsTeam.json'
  workflowPath: '.github/workflows/clopsteam.coreinfra.deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  job_static_validation:
    name: 'Preflight Validation'
    runs-on: ubuntu-20.04
    environment: stg
    steps:
      # Checkout code
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    # Run analysis by using the PSRule GitHub action.
    - name: Run PSRule analysis
      uses: microsoft/ps-rule@v2.4.0
      continue-on-error: true # Setting this whilst PSRule gets bedded in, in this project
      with:
        modules: 'PSRule.Rules.Azure'
        # inputPath: ${{ env.solutionPath }}
        inputType: repository
        outputFormat: Csv
        outputPath: '${{ env.solutionPath }}-PSRule-output.csv'

    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        scope: ${{ env.scope }}
        region: ${{ env.region }}
        template: ${{ env.solutionPath }}/main.bicep
        parameters: ${{ env.solutionDeploymentParamsPath }} environment=stg location=${{ env.region }}
        deploymentMode: Validate
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"


  job_deploy_to_staging:
    needs:
    - job_static_validation
    environment: stg
    runs-on: ubuntu-20.04
    name: 'Deploy to Staging for Validation'
    steps:

    # Checkout code
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: ${{ env.scope }}
        region: ${{ env.region }}
        template: ${{ env.solutionPath }}/main.bicep
        parameters: ${{ env.solutionDeploymentParamsPath }} environment=stg location=${{ env.region }}
        failOnStdErr: false
        deploymentMode: Complete

    - run: echo ${{ steps.deploy.outputs }}
