name: 'Deploy CoreInfra'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: 'Remove deployed module'
        required: false
        default: false
  push:
    branches:
      - demo/submodule
    paths:
      - '.github/workflows/coreinfra.submodule.deploy.yml'
      - 'CoreInfra/**'

env:
  environment: 'dev'
  region: 'eastus'
  resourceGroupName: 'CoreInfraBicepLive'
  modulePath: 'CoreInfra'
  workflowPath: '.github/workflows/coreinfra.deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main
    - name: Checkout BicepModulesDemo submodule
      run: git submodule update --init --recursive

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: debug
      run: |
        ls -al
        ls -al BicepModulesDemo
        ls -al CoreInfra

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        region: ${{ env.region }}
        template: '${{ env.modulePath }}/main.bicep'
        parameters: ${{ env.modulePath }}/parameters/${{ env.environment }}.json ${{ env.modulePath }}/parameters/shared.json
        failOnStdErr: false
        
    - run: echo ${{ steps.deploy.outputs.* }}
