name: 'Deploy CoreInfra'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: 'Remove deployed module'
        required: false
        default: false
  push:
    branches:
      - main
    paths:
      - '.github/workflows/coreinfra.deploy.yml'
      - 'CoreInfra/**'

env:
  modulePath: 'CoreInfra'
  workflowPath: '.github/workflows/coreinfra.deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/actions/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}


      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: '${{ env.modulePath }}/main.bicep'
        parameters: '${{ env.modulePath }}/dev.json'
        failOnStdErr: false
        
    - run: echo ${{ steps.deploy.outputs.containerName }}
